// <auto-generated />
using EF_RECEIPT.Model.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_RECEIPT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_RECEIPT.Model.Entities.ChiTietPhieuThu", b =>
                {
                    b.Property<int>("ChiTietPhieuThuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietPhieuThuID"));

                    b.Property<int>("NguyenLieuID")
                        .HasColumnType("int");

                    b.Property<int>("PhieuThuID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("ChiTietPhieuThuID");

                    b.HasIndex("NguyenLieuID");

                    b.HasIndex("PhieuThuID");

                    b.ToTable("ChiTietPhieuThu");
                });

            modelBuilder.Entity("EF_RECEIPT.Model.Entities.LoaiNguyenLieu", b =>
                {
                    b.Property<int>("LoaiNguyenLieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiNguyenLieuID"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LoaiNguyenLieuID");

                    b.ToTable("LoaiNguyenLieu");
                });

            modelBuilder.Entity("EF_RECEIPT.Model.Entities.NguyenLieu", b =>
                {
                    b.Property<int>("NguyenLieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguyenLieuID"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<int>("LoaiNguyenLieuID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongKho")
                        .HasColumnType("int");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NguyenLieuID");

                    b.HasIndex("LoaiNguyenLieuID");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("EF_RECEIPT.Model.Entities.PhieuThu", b =>
                {
                    b.Property<int>("PhieuThuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhieuThuID"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NgayLap")
                        .HasColumnType("int");

                    b.Property<string>("NhanVienLap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.HasKey("PhieuThuID");

                    b.ToTable("PhieuThu");
                });

            modelBuilder.Entity("EF_RECEIPT.Model.Entities.ChiTietPhieuThu", b =>
                {
                    b.HasOne("EF_RECEIPT.Model.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("ChiTietPhieuThu")
                        .HasForeignKey("NguyenLieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_RECEIPT.Model.Entities.PhieuThu", "PhieuThu")
                        .WithMany("ChiTietPhieuThu")
                        .HasForeignKey("PhieuThuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("PhieuThu");
                });

            modelBuilder.Entity("EF_RECEIPT.Model.Entities.NguyenLieu", b =>
                {
                    b.HasOne("EF_RECEIPT.Model.Entities.LoaiNguyenLieu", "LoaiNguyenLieu")
                        .WithMany()
                        .HasForeignKey("LoaiNguyenLieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNguyenLieu");
                });

            modelBuilder.Entity("EF_RECEIPT.Model.Entities.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietPhieuThu");
                });

            modelBuilder.Entity("EF_RECEIPT.Model.Entities.PhieuThu", b =>
                {
                    b.Navigation("ChiTietPhieuThu");
                });
#pragma warning restore 612, 618
        }
    }
}
