//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_RECEIPT.Model.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EF_RECEIPT.Model.Helper.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don Vi Tinh:.
        /// </summary>
        internal static string DonViTinh {
            get {
                return ResourceManager.GetString("DonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loi nhap du lieu khong hop le!.
        /// </summary>
        internal static string Err {
            get {
                return ResourceManager.GetString("Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi Chu:.
        /// </summary>
        internal static string GhiChu {
            get {
                return ResourceManager.GetString("GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia Ban:.
        /// </summary>
        internal static string GiaBan {
            get {
                return ResourceManager.GetString("GiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loai Nguyen Lieu ID:.
        /// </summary>
        internal static string LoaiNguyenLieuID {
            get {
                return ResourceManager.GetString("LoaiNguyenLieuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay Lap:.
        /// </summary>
        internal static string NgayLap {
            get {
                return ResourceManager.GetString("NgayLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyen Lieu ID:.
        /// </summary>
        internal static string NguyenLieuID {
            get {
                return ResourceManager.GetString("NguyenLieuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhan Vien Lap:.
        /// </summary>
        internal static string NhanVienLap {
            get {
                return ResourceManager.GetString("NhanVienLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phieu Thu ID:.
        /// </summary>
        internal static string PhieuThuID {
            get {
                return ResourceManager.GetString("PhieuThuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So Luong Ban:.
        /// </summary>
        internal static string SoLuongBan {
            get {
                return ResourceManager.GetString("SoLuongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So Luong Kho:.
        /// </summary>
        internal static string SoLuongKho {
            get {
                return ResourceManager.GetString("SoLuongKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten Nguyen Lieu:.
        /// </summary>
        internal static string TenNguyenLieu {
            get {
                return ResourceManager.GetString("TenNguyenLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuc hien thanh cong!.
        /// </summary>
        internal static string ThanhCong {
            get {
                return ResourceManager.GetString("ThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Tien:.
        /// </summary>
        internal static string ThanhTien {
            get {
                return ResourceManager.GetString("ThanhTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co loi khi thao tac!.
        /// </summary>
        internal static string ThatBai {
            get {
                return ResourceManager.GetString("ThatBai", resourceCulture);
            }
        }
    }
}
